name: Deploy prod

on:
  push:
    tags:
      - '*'

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.check-tag.outputs.valid }}
    steps:
      - name: Extraer y validar tag semver (X.Y.Z)
        id: check-tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "Tag recibido: $TAG"
          if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "valid=true" >> "$GITHUB_OUTPUT"
          else
            echo "valid=false" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

  deploy:
    needs: validate-tag
    if: needs.validate-tag.outputs.valid == 'true'
    uses: RunOnGrid/deploy-workflow/.github/workflows/deploy-prod-1p.yml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN_PROD: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_PROD }}
      OP_ITEM_ENVFILE_NAME: ${{ secrets.OP_ITEM_ENVFILE_NAME }}